from pydantic import BaseModel, ConfigDict, Field
from uuid import UUID
from typing import Optional

# This file defines the schemas for planned exercises that belong to routine days.
# These exercises are created by trainers or generated by AI and assigned to users' routines.

class ExerciseBase(BaseModel):
    name: str
    sets: int = Field(ge=1)
    reps: int = Field(ge=1)
    weight_suggestion: float = Field(ge=0)
    rest_seconds: int = Field(ge=0)
    video_url: Optional[str] = None  # Optional YouTube or external link
    notes: Optional[str] = None      # Trainer/AI notes for execution

class ExerciseCreate(ExerciseBase):
    routine_day_id: UUID

class ExerciseOut(ExerciseBase):
    id: UUID
    routine_day_id: UUID
    model_config = ConfigDict(from_attributes=True)